### ISSUE TITLE
ROS2 and DDS ,UDP communication in TWO different PC

### ISSUE THREAD

**Issue by golizheh** [eProsima/SOSS-DDS#16]
Hi,

Could you please provide a helloworld example of using soss-DDS? If in PC1 we  have FASTRTPS which is runs Hellowrold example and in the PC2 we have ROS2 which is runs Talker.
PC2 Run:ROS2 Talker/Listener example.
PC1 Run: Fast RTPS HelloWorld example.
And we also have ross  for communication between this two.(YAML files and topics)

I think it is makes job much more clear.
Thanks for your help
With Best Regards

**Comment by golizheh** [comment]
Hi@lemunozm
Could you please help me the compiler error issue?

When I building(UBUNTU 18) (colcon build --packages-up-to soss-dds soss-ros2) I will get the following error:
Starting >>> soss-core
--- stderr: soss-core
/home/golizheh/soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp: In constructor ‘soss::MiddlewareInterfaceExtension::Implementation::Implementation(YAML::Node, const string&)’:
/home/golizheh/soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp:81:5: error: ‘assert’ was not declared in this scope
assert(_directory.is_absolute());
^~~~~~
/home/golizheh/soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp:81:5: note: suggested alternative: ‘qsort’
assert(_directory.is_absolute());
^~~~~~
qsort
make[2]: *** [CMakeFiles/soss-core.dir/src/MiddlewareInterfaceExtension.cpp.o] Error 1
make[1]: *** [CMakeFiles/soss-core.dir/all] Error 2
make: *** [all] Error 2

Failed <<< soss-core [ Exited with code 2 ]

Summary: 0 packages finished [7.09s]
1 package failed: soss-core
1 package had stderr output: soss-core
3 packages not processed

**Comment by lemunozm** [comment]
I answered you in the related issue: https://github.com/eProsima/SOSS-DDS/issues/17

**Comment by golizheh** [comment]
Thank you I will close this isue

**Comment by golizheh** [comment]
Dear @lemunozm I just have a short question about communication: 
As I mentioned above:
I have two pc. 
PC1: Has SOSS and ROS2 installed
PC2: Just FastRTPS v1.7 installed PC2 (Publisher): 
I have run Dynamic HelloWorld example in PC2 and get following output: 

./DynamicHelloWorldExample publisher 
Starting Publisher running 10 samples. 
Participant RTPSParticipant discovered
Participant soss_ros2 discovered 
Participant _ros2cli_18265 discovered 

In PC1: I have run SOSS and ROS2 subscriber for this message

 $ soss dds_ros2.yaml [soss-dds]: participant not provided in configuration file. UDP default participant will be created. 
[soss-dds]: configured! 
[soss-dds]: publisher created. topic: hello_dds, type: std_msgs/String 
[soss-dds]: subscriber created. topic: hello_ros2, type: std_msgs/String 


But it is look like SOSS can not understand that there is a publisher in **another pc With another Ip address**

 Should I make or add configuration file or specify IP address (for first test I just want to have **UDP** communication)?

I have also used "https://github.com/eProsima/SOSS-DDS/blob/master/dds/sample/tcp/dds_tunnel_ros2_fiware_client.yaml" with "Config.xml" (I have update the part "Address" with my IP address ) (I know it tries to have a TCP communication)but still there is no communication between two pc?

I also change my Setup and Having SOSS installed in two pc installed but still no communication.
Maybe  I am wrong in one the way of communication between this two:
Two PC are in the same network and I do not think there is Firewall problem.

**Because I have already start this issue I deiced to continue with issue. 
Please feel free if you want to open another issue relevant with this one.

thanks in advance and look forward to hearing from you

**Comment by lemunozm** [comment]
Hi @golizheh,

the publisher discover a `RTPSParticipant` that means a default UDP participant (that probably refers to the soss UDP default participant) has been discovered. So the publisher is able to discover the soss participant but not the soss subscriber (that usually means that the topic or the type differs). 
Could you confirm that it works if Publisher is running in PC1?

Regarding TCP communication, could you confirm the next setup?:
```
ros2(pc1) -> soss(pc1) -> soss(pc2) -> fast(pc2)
```

**Comment by golizheh** [comment]
Hi @lemunozm 
UDP:
Yes as you said Publisher in PC1 can discover SOSS and Subscriber in PC2.
BUT SOSS and subscriber in PC2 can not have communication with PC1 publisher. (regarding topic and type I have used the same YAML file and also DynamicHellowWorld file in which was already worked in the One PC)

TCP:
ros2(pc1) -> soss(pc1) -> soss(pc2) -> fast(pc2) Yes.
BUt firstly could you please help me with UDP? if I am wrong some where,

Thanks

**Comment by lemunozm** [comment]
In UDP, if you test `ros2(PC1) <--> soss (PC1) <--> fast(PC1)` (all in the same PC, and both directions), then everything works?

**Comment by golizheh** [comment]
Yes in the one PC everything is working very good, but 

fastrtps (PC1) -- soss(pc2) --- ROS2 (pc2) is not working 
 FastRTPS in PC1 can dicover SOSS (PC2) and ROS (pc2) but SOSS (PC2) can not have communication with FastrtPS (PC1) so => there is no message in ROS2

**Comment by lemunozm** [comment]
It is weird because if both PCs are in the same network, the behaviour will be the same as being in the same PC. We will test your scenario on our computers and will let you know.

**Comment by golizheh** [comment]
Thanks 
look forward to hearing from you

**Comment by lemunozm** [comment]
Hi @golizheh, 

Could you confirm us that you have fastrtps(PC1)-fastrpts(PC2) communication? 
SOSS-DDS plugin inside of SOSS uses fastrtps inside. So the underlying communication is fast-fast.

Thanks

**Comment by golizheh** [comment]
Hi @lemunozm 
You mean just run fastRTPS (PC1) publisher and FastRTPS (PC2) Subscriber  and see if it is works?
Is it Ok to test it with DynamciHellowworld?

Thanks and Look forward to hearing from you

**Comment by lemunozm** [comment]
It is ok to test with the DynamicHelloWorld modified in the branch I sent you.

**Comment by lemunozm** [comment]
Also, if it looks like there is no communication, please wait for 40 seconds. It will mean that the multicast initial multicast discovery message has been lost, and fastrtps is waiting for the periocity announcement (default 40 seconds).

**Comment by golizheh** [comment]
Dear @lemunozm 

I have test with With Fast RTPS:
PC1: $ ./DynamicHelloWorldExample publisher
Starting
Publisher running 10 samples.
Participant DynString_sub discovered

PC2: ./DynamicHelloWorldExampl subscriber
Starting 
Subscriber running. Please press enter to stop the Subscriber

As it is clear subscriber can not get any thing,
Do you think it is because v7 problem?

**Comment by lemunozm** [comment]
Maybe is a fast v7 problem, we are testing this problem here. Could you confirm that the problem persists after 40 seconds of both Publisher and Subscriber has been running?

**Comment by golizheh** [comment]
Yes I have wait also for more than 40 sec.

**Comment by lemunozm** [comment]
> Dear @lemunozm
> 
> I have test with With Fast RTPS:
> PC1: $ ./DynamicHelloWorldExample publisher
> PC2: ./HelloWorldExample subscriber

I see here that you are using as a Publisher from DynamicHelloWorldExample and a Subscriber from HelloWorldExample. Please, use the same example (because the topic and types differs), and ensure that both fastrtps are in the same branch/commit.

**Comment by golizheh** [comment]
yes I have test it with same program  DynamicHelloWorld
sorry for mistake in copy pasting, it is updated

**Comment by lemunozm** [comment]
The topic name of both publisher and subscriber is the same? When I created the branch `example/helloword-ros2-conversion` (that I suppose you are using) the publisher has the topic name `hello_ros2` and subscriber has `hello_dds` to match with the soss example names.
 
Use the same topic name for both (pub and sub), and recompile again. 

The main problems when the publishers and subscribers not matching are:
- They are not at the same local network.
- Topic names differ
- Type names differ

**Comment by golizheh** [comment]
Yes I update everything and check everything and every thing is same.
Do you test it in your setup? with v7?

**Comment by golizheh** [comment]
In one PC everything is works,

Firos2 which is used V1.9 is works also fine to publisher from FastRTps and Subscriber and ROS2 is subscriber, so my network and port does not have problem

**Comment by lemunozm** [comment]
> Yes I update everything and check everything and every thing is same.
> Do you test it in your setup? with v7?

Yes, we have tested in our setup and works (inside of the 40 seconds interval that can be configured later). Check if the compilation examples are updated with the current branch, maybe the installation in the second PC has some kind of errors or differs from the first PC installation.

It should work in your setup. :thinking:

**Comment by golizheh** [comment]
I try to reinstall everything again and after compiling Dynamic Heloworld file, when I want to run it I will ge the follwoing error:

./DynamicHelloWorldExample  publisher
./DynamicHelloWorldExample: error while loading shared libraries: libfastcdr.so.1: cannot open shared object file: No such file or directory

It is Ubuntu 18.04 and I install everything from begining again.
BuT I was able to send and receive command with Helloworld example in two computer.

**Comment by lemunozm** [comment]
Do you compile it with the third-party available? 
Supposing you are in `Fast-RTPS/build` folder:
```
cmake .. -DTHIRDPARTY=ON -DCOMPILE_EXAMPLES=ON
```
The third-party flag will download the fastrtps dependencies within your project.

**Comment by golizheh** [comment]
I have do it now, but again same problem.

**Comment by golizheh** [comment]
Dear @lemunozm 

Please accept my special thanks for your help and support, my problem is solve.
