### ISSUE TITLE
colcon build error at soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp:81:36  error: ‘assert’ was not declared in this scope      assert(_directory.is_absolute());

### ISSUE THREAD

**Issue by golizheh** [eProsima/SOSS-DDS#17]
Hi,

When I building(UBUNTU 18)  I will get the following error:
Starting >>> soss-core
--- stderr: soss-core
soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp: In constructor ‘soss::MiddlewareInterfaceExtension::Implementation::Implementation(YAML::Node, const string&)’:soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp:81:5: error: ‘assert’ was not declared in this scope

make[2]: *** [CMakeFiles/soss-core.dir/src/MiddlewareInterfaceExtension.cpp.o] Error 1
make[1]: *** [CMakeFiles/soss-core.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< soss-core  [ Exited with code 2 ]

Summary: 0 packages finished [7.09s]
  1 package failed: soss-core
  1 package had stderr output: soss-core
  3 packages not processed

**Comment by lemunozm** [comment]
Hi @golizheh,
Try to open the `/home/golizheh/soss_wp/src/soss/packages/core/src/MiddlewareInterfaceExtension.cpp` file and write in the top of the file the folowwing:
```c
#include <cassert>
```

**Comment by golizheh** [comment]
Hi @lemunozm 
It is also can not find another file.

soss_wp/install/soss-core/include/soss/SystemHandle.hpp:24:10: fatal error: yaml-cpp/yaml.h: No such file or directory
 #include <yaml-cpp/yaml.h>

**Comment by lemunozm** [comment]
You need to install `yaml-cpp` in your computer or add it as a colon package.
The easiest way is installing: `sudo apt install libyaml-cpp-dev`

Probably, the `yaml-cpp` includes `cassert` or `assert.h` and the previous change is innecesary once you include the yaml library

**Comment by golizheh** [comment]
Thanks for your help
