### ISSUE TITLE
Segmentaion fault

### ISSUE THREAD

**Issue by golizheh** [eProsima/SOSS-DDS#19]
Hi,

I just have a question regarding communication between Fastrps in one computer and ROS2 in another computer. 
I have used YAML file sample directory:
systems:
    dds:
      type: dds
      dynamic types:
        struct std_msgs__String:
          string: "data"

    ros2:
      type: ros2

routes:
    ros2_to_dds: { from: ros2, to: dds }
    dds_to_ros2: { from: dds, to: ros2 }

topics:
    hello_ros2: { type: "std_msgs/String", route: dds_to_ros2 }
    hello_dds: { type: "std_msgs/String", route: ros2_to_dds }

and when I run: soss dds_ros2.yaml
I have get an error : segmentaion fault (core dumped)

As it is shown in the document which is attahced I have following setup and I want to transfer message between fastrtps and ROS2 (For starting point let say both are in the same machine)
[example.docx](https://github.com/eProsima/SOSS-DDS/files/3728894/example.docx)

Could you please provide me some help in this issue?

**Comment by golizheh** [comment]
I have also tried with config.xml file in dds/sample/tcp folder, it is said the file need to be a map contrariness for topic and service and ect... which is sound OK.
Maybe the format should something in XML file NOT YAML file, because no one of the YAML file can be executed.

**Comment by lemunozm** [comment]
Hi, which commit of soss are you using?
Currently the DDS System handle supports the this version:
https://github.com/osrf/soss/tree/660078e9fee9fca1b3094d62dc6a22d4a1e80a38

(The commit is linked at the top of the README.md of soss-dss)

**Comment by golizheh** [comment]
I have run soss comand,
When I run soss-dds test.yaml : it said  soss-dds command not find,
I have already run install/local-setup.bash file.
I run:

soss myfile.yaml   

Other commands does not work. I have also checked  video for firware, it is looks like it is also run soss command but in my case it is return back an error.

**Comment by golizheh** [comment]
Dear @lemunozm 
I have update git repository and previous error is gone. Thanks

But when I  do the following:
Source path/to/ros2_ws
source path/to/localsetup.bash      (For soss)
ssos myfile.yaml

Then I will get the follwoing error:

[soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
soss-ros2 could not find .mix file for message type: std_msgs/String
 -- Make sure that you have generated the soss-ros2 extension for that message type by calling soss_rosidl_mix(PACKAGES <package> MIDDLEWARES ros2) in your build system!
Failed to load middlewares!

I have installed latest fastrtps, could you please tell me how can I check the version of it, if this issue is relevant to fastrtps?

Thanks

**Comment by lemunozm** [comment]
Hi @golizheh, your last issue is not related to fastrtps, this issue: https://github.com/eProsima/SOSS-DDS/issues/21 has the solution to solve it.

Close this issue.
